import CoreGraphics
import Foundation

@MainActor
protocol ActionExecutor {
    func execute(_ actions: [Action]) throws
}

extension Action {
    var keyboardShortcut: KeyboardShortcut {
        switch self {
        case .previousSpace: KeyboardShortcut(keyCode: 123)
        case .nextSpace: KeyboardShortcut(keyCode: 124)
        case .missionControl: KeyboardShortcut(keyCode: 126)
        case .shortcut(let shortcut): shortcut
        }
    }
}

@MainActor
struct ActionEngine: ActionExecutor {
    // System hotkeys must enter the HID event stream, before session routing.
    // Keep both the event and destination injectable: tests never post input.
    var post: (CGEvent, CGEventTapLocation) -> Void = { $0.post(tap: $1) }
    var canPost: () -> Bool = { CGPreflightPostEventAccess() }

    func execute(_ actions: [Action]) throws {
        guard canPost() else {
            throw ActionDispatchError.accessibilityRequired
        }
        for action in actions {
            let shortcut = action.keyboardShortcut
            guard shortcut.keyCode <= 127,
                  let source = CGEventSource(stateID: .privateState) else {
                throw PeripheralKitError.invalidConfiguration("Impossibile creare la scorciatoia.")
            }
            let modifiers: [(Bool, CGKeyCode, CGEventFlags)] = [
                (shortcut.control, 59, .maskControl),
                (shortcut.option, 58, .maskAlternate),
                (shortcut.shift, 56, .maskShift),
                (shortcut.command, 55, .maskCommand),
            ]
            let pressed = modifiers.filter { $0.0 }
            var flags: CGEventFlags = []
            var events: [CGEvent] = []
            func append(_ key: CGKeyCode, down: Bool, modifier: Bool = false) throws {
                guard let event = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: down) else {
                    throw PeripheralKitError.invalidConfiguration("Impossibile creare la scorciatoia.")
                }
                // Explicit modifier transitions are required by CGEventCreateKeyboardEvent.
                // Keep the intrinsic arrow-key flags generated by Quartz.
                let intrinsic = modifier ? CGEventFlags() : event.flags.intersection([.maskNumericPad, .maskSecondaryFn])
                event.flags = flags.union(intrinsic)
                if modifier { event.type = .flagsChanged }
                event.setIntegerValueField(.eventSourceUserData, value: InputEventEngine.syntheticMarker)
                events.append(event)
            }
            for (_, key, flag) in pressed {
                flags.insert(flag)
                try append(key, down: true, modifier: true)
            }
            try append(shortcut.keyCode, down: true)
            try append(shortcut.keyCode, down: false)
            for (_, key, flag) in pressed.reversed() {
                flags.remove(flag)
                try append(key, down: false, modifier: true)
            }
            // Construct the complete sequence first so allocation failure cannot
            // leave a modifier pressed. Release every modifier in reverse order.
            for event in events { post(event, .cghidEventTap) }
        }
    }
}

enum ActionDispatchError: LocalizedError {
    case accessibilityRequired

    var errorDescription: String? {
        "macOS non consente l'invio delle scorciatoie. Autorizza PeripheralKit in Privacy e sicurezza → Accessibilità, poi riapri l'app."
    }
}
